global_config:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'image-detection-api'
    environment: 'production'

scrape_configs:
  - job_name: 'image-detection-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
